#!/usr/bin/python3

from fabric.api import local

def do_it():
    author = "Lucho"
    git_hub = "LuisPatino92"
    local("tar -xzf core.tgz -C ./")
    with open('readme_file.txt', 'r', encoding='utf-8') as f:
        for line in f.readlines():
            repo = line.split(" ")[1].split("/")[0]
            directory = line.split(" ")[1].split("/")[1][0:-1]
            print(directory)
            original_name = "core/{}___{}".format(repo, directory)
            local("sed -i 's/Lucho Patino/{}/g' {}".format(author, original_name))
            local("sed -i 's/LuisPatino92/{}/g' {}".format(git_hub, original_name))
            local("mv {} ../{}/{}/README.md".format(original_name, repo, directory))
            local("cd /root/Hbtn_Projects/{}/{} && \
                    git add README.md &&\
                    git commit -m 'Readme generated by a script made by LazyDevs' &&\
                    git push \
                    ".format(repo, directory))
            local("rm -rf core")
